# Generated by Django 2.0.2 on 2018-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(verbose_name='Time input in 24hr format,         e.g. 17:30 = 5:30 pm'),
        ),
    ]
